spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=disabled
spring.security.user.password=disabled
spring.datasource.url=YOUR_DB_URL
spring.datasource.username=YOUR_USER
spring.datasource.password=YOUR_PASS

server.port=${PORT:8080}