spring.jpa.hibernate.ddl-auto=update
spring.main.allow-bean-definition-overriding=true

# PostgreSQL Configuration for Neon (Production)
spring.datasource.url=jdbc:postgresql://ep-summer-smoke-apr2sdff.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_GCuTqRWU24xg
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

server.port=${PORT:8080}